import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const list = [
  "AgeCalculator.astro",
  "ArmedForcesPensionSchemeCalculator.astro",
  "BankOverdraftCostCalculator.astro",
  "BirthdayDayOfWeekStarSignFinderCalculator.astro",
  "BitcoinInGbpExchangeCalculator.astro",
  "BmiBmrCalorieCalculator.astro",
  "BodyFatPercentageEstimator.astro",
  "BudgetCalculator503020Rule.astro",
  "BusinessValuationCalculator.astro",
  "BuyToLetStampDutySurchargeCalculator.astro",
  "CapitalGainsTaxOnSharesCalculator.astro",
  "CapitalRepaymentMortgageCalculator.astro",
  "CarDepreciationEstimator.astro",
  "CarLeasingVsPcpFinanceComparisonCalculator.astro",
  "ChildcareVouchersVsTaxFreeChildcareCalculator.astro",
  "CommercialLeaseServiceChargeSquareFootageCalculator.astro",
  "CompanyCarTaxBikCalculator.astro",
  "CompoundInterestCalculator.astro",
  "CryptoTaxCalculatorHmrcRules.astro",
  "CurrencyConverter.astro",
  "DailyWaterHydrationIntakeCalculator.astro",
  "DateDurationDayCounterCalculator.astro",
  "DegreeClassificationBoundaryEstimator.astro",
  "DiscountSaleSavingsCalculator.astro",
  "DividendTaxCalculator.astro",
  "EarlyPaymentDiscountCalculator.astro",
  "ElectricityCostApplianceRunningCostCalculator.astro",
  "ElectricVehicleEvChargingCostRangeCalculator.astro",
  "FirefightersPensionSchemeUkCalculator.astro",
  "FixedMortgageRateTermComparatorCalculator.astro",
  "FlightTimeTimeDifferenceCalculator.astro",
  "ForwardMortgageRateLockEstimator.astro",
  "FuelCostJourneyMileageCalculator.astro",
  "FurloughPayRecalculationHistoricalEstimator.astro",
  "HelpToSaveSchemeCalculator.astro",
  "HmrcLateTaxPaymentPenaltyInterestCalculator.astro",
  "HmrcPaymentOnAccountTaxBillCalculator.astro",
  "HomeEnergyEfficiencyGrantsCalculator.astro",
  "HowMuchHouseCanIAffordCalculator.astro",
  "IdealBodyWeightPredictor.astro",
  "ImperialToMetricUnitConverter.astro",
  "ImportDutyVatCalculator.astro",
  "IndexFundEtfInvestmentCalculator.astro",
  "InflationPurchasingPowerCalculator.astro",
  "InsolvencyDebtSolutionSelectorCalculator.astro",
  "LifetimeIsaFirstHomeCalculator.astro",
  "LimitedCompanySetupCostsCalculator.astro",
  "LtvLoanToValueBracketCalculator.astro",
  "MortgageDelayOfferValidityEstimator.astro",
  "MortgageOutstandingBalanceEstimator.astro",
  "MortgageOverpaymentSavingsCalculator.astro",
  "MortgageStressTestAffordabilityCalculator.astro",
  "MotCostRepairBudgetCalculator.astro",
  "NorthernIrelandDogLicenceCostCalculator.astro",
  "NorthernIrelandRatesDomesticRatingPropertyTaxCalculator.astro",
  "P11dBenefitInKindBiKTaxCalculator.astro",
  "PaypalUkFeesCalculator.astro",
  "PensionDrawdownCapitalDepletionCalculator.astro",
  "PercentageCalculator.astro",
  "PersonalLoanCalculator.astro",
  "PolicePensionSchemeUkCalculator.astro",
  "ProfitMarginMarkupCalculator.astro",
  "RemortgageProductTransferCalculator.astro",
  "RepaymentVsInterestOnlyMortgageComparisonCalculator.astro",
  "RightToBuyCouncilHouseDiscountCalculator.astro",
  "RoiReturnOnInvestmentCalculator.astro",
  "RoiRoiPACalculator.astro",
  "RuleOfThreeDreisatzMathCalculator.astro",
  "RunningPaceRaceTimePredictor.astro",
  "SavingsTargetGrowthCalculator.astro",
  "ScaleModelMapConverter.astro",
  "ScottishCouncilTaxBandsMultiplierCalculator.astro",
  "ScottishHighersToUcasTariffPointsConverter.astro",
  "ScottishLandAndBuildingsTransactionTaxLbttCalculator.astro",
  "ScottishSelfEmployedIncomeTaxVsRestOfUkCalculator.astro",
  "SelfEmployedClass2Class4NationalInsuranceCalculator.astro",
  "SelfInvestedPersonalPensionSippCalculator.astro",
  "SharedOwnershipRentAndServiceChargeCalculator.astro",
  "SmallBusinessVatFlatRateSchemeVsStandardCalculator.astro",
  "SocialSecurityScotlandCarersAllowanceSupplementCalculator.astro",
  "SoleTraderTaxReserveBudgetCalculator.astro",
  "SoleTraderVsLtdCompanyRegistrationFeesCalculator.astro",
  "SolicitorFeesEstimator.astro",
  "SortCodeAccountNumberToIbanConverter.astro",
  "StatutoryLatePaymentInterestCalculator.astro",
  "StatutoryMaternityPaySmpEligibilityCalculator.astro",
  "StatutoryPaternityPaySppCalculator.astro",
  "StatutoryRedundancyPaymentCalculator.astro",
  "StudentGradePointAverageGpaPercentageConverter.astro",
  "StudentMaintenanceGrantLoanEligibilityCalculator.astro",
  "TeachersPensionSchemeUkCalculator.astro",
  "TimeZoneCalculator.astro",
  "TippingServiceChargeCalculator.astro",
  "TuitionFeeLoanInterestCompoundingEstimator.astro",
  "UnfairDismissalEmploymentTribunalCompensationCalculator.astro",
  "UniversalCreditScottishWorkAllowanceCalculator.astro",
  "UniversitiesCollegesAdmissionsServiceUcasPointsCalculator.astro",
  "UsedCarInspectionBudgetCalculator.astro",
  "VehicleStatutoryOffRoadNotificationSornEstimator.astro",
  "WeddingBudgetPlanner.astro",
  "WelshLandTransactionTaxLttCalculator.astro"
];

// Map filename to kebab-case URL slug
const urls = list.map(file => {
  const name = file.replace('.astro', '');
  const kebab = name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
  return `http://localhost:4321/${kebab}/`;
});

console.log(urls.join('\n'));
